---
group: bionic
language: python
python: "3.7"
env:
  global:
    - ANSIBLE_MODULE_UTILS=$TRAVIS_BUILD_DIR/module_utils
  matrix:
  - SCENARIO=debian
  - SCENARIO=ubuntu
  - SCENARIO=centos
  - SCENARIO=fedora
  - SCENARIO=amazonlinux

matrix:
  fast_finish: true

services: docker
addons:
  apt:
    packages:
      - docker-ce
cache:
  pip: true
  directories:
    - ~/.cache/pipenv
install:
  - pip install pipenv
  - pipenv install --two --dev
  - gem install rubocop -v 0.80.1
script:
  - pipenv run molecule --base-config molecule/shared/base.yml test --scenario-name $SCENARIO --driver-name docker --destroy always

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
